# Generated by Django 3.2.4 on 2021-06-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99'}}, help_text='Maximum 9999.99', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='M', max_length=10)),
                ('color', models.CharField(choices=[('White', 'white'), ('Black', 'black'), ('Wood', 'wood')], default='Black', max_length=10)),
                ('paper_type', models.CharField(choices=[('Glossy', 'glossy'), ('Mate', 'mate')], default='Glossy', max_length=10)),
                ('quantity', models.IntegerField(error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99'}}, help_text='Maximum 10')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.cart')),
            ],
        ),
    ]
